from .analisys_fastest_laps import analisys_fastest_laps
from .analisys_race_position_evolution import analisys_race_position_evolution
from .analisys_team_performace import analisys_team_performace
from .analisys_race_pace import analisys_race_pace
from .analisys_lap_time_average import analisys_lap_time_average
from .analisys_top_speed import analisys_top_speed
from .analisys_track_dominance import analisys_track_dominance